puts "Start -- Create Golfers"
# Golfer.create(name: "Tommy", age: 38, player_handicap: nil) 
# Golfer.create(name: "Danny", age: 34, player_handicap: nil)
# Golfer.create(name: "Chris", age: 44, player_handicap: nil)
# Golfer.create(name: "Steve", age: 35, player_handicap: nil)
# Golfer.create(name: "Connor", age: 22, player_handicap: nil)
# Golfer.create(name: "Brian Mc", age: 40, player_handicap: nil)
# Golfer.create(name: "Kevin", age: 36, player_handicap: nil)
# Golfer.create(name: "Josh", age: 43, player_handicap: nil)
# Golfer.create(name: "Rob", age: 40, player_handicap: nil)
# Golfer.create(name: "Brian D", age: 34, player_handicap: nil)
# Golfer.create(name: "Patrick", age: 34, player_handicap: nil)
# Golfer.create(name: "Uncle Thomas", age: 70, player_handicap: nil)
# Golfer.create(name: "Uncle Franny", age: 62, player_handicap: nil)
# Golfer.create(name: "Uncle Brendan", age: 61, player_handicap: nil)
# Golfer.create(name: "Uncle PJ", age: 65, player_handicap: nil)
# Golfer.create(name: "Uncle Marty", age: 64, player_handicap: nil)
# Golfer.create(name: "Rory", age: 28, player_handicap: nil)
# Golfer.create(name: "Colin Kelly", age: 30, player_handicap: nil)
# Golfer.create(name: "Jimmy Kelly", age: 26, player_handicap: nil)
# Golfer.create(name: "Sean", age: 36, player_handicap: nil)
puts "End --- Creates Golfers"

puts "Start --- Creates Courses"
# Course.create(name: "Ocean Acres Golf Club", address: "925 buccaneer Lane, Manahawkin, NJ 08050", phone_number: "(609) 597-9393", url: "http://www.oceanacrescc.com")
puts "End --- Creates Courses"


puts "Start --- Creates Holes"
# Hole.create(hole_number: 1, course_id: 1, distance: 468, hole_handicap: 13, par: 5)
# Hole.create(hole_number: 2, course_id: 1, distance: 315, hole_handicap: 9, par: 4)
# Hole.create(hole_number: 3, course_id: 1, distance: 365, hole_handicap: 15, par: 4)
# Hole.create(hole_number: 4, course_id: 1, distance: 353, hole_handicap: 5, par: 4)
# Hole.create(hole_number: 5, course_id: 1, distance: 368, hole_handicap: 3, par: 4)
# Hole.create(hole_number: 6, course_id: 1, distance: 183, hole_handicap: 11, par: 3)
# Hole.create(hole_number: 7, course_id: 1, distance: 503, hole_handicap: 7, par: 5)
# Hole.create(hole_number: 8, course_id: 1, distance: 149, hole_handicap: 17, par: 3)
# Hole.create(hole_number: 9, course_id: 1, distance: 411, hole_handicap: 1, par: 4)
# Hole.create(hole_number: 10, course_id: 1, distance: 155, hole_handicap: 12, par: 3)
# Hole.create(hole_number: 11, course_id: 1, distance: 318, hole_handicap: 10, par: 4)
# Hole.create(hole_number: 12, course_id: 1, distance: 409, hole_handicap: 2, par: 4)
# Hole.create(hole_number: 13, course_id: 1, distance: 175, hole_handicap: 6, par: 3)
# Hole.create(hole_number: 14, course_id: 1, distance: 300, hole_handicap: 14, par: 4)
# Hole.create(hole_number: 15, course_id: 1, distance: 506, hole_handicap: 8, par: 5)
# Hole.create(hole_number: 16, course_id: 1, distance: 330, hole_handicap: 16, par: 4)
# Hole.create(hole_number: 17, course_id: 1, distance: 387, hole_handicap: 4, par: 4)
# Hole.create(hole_number: 18, course_id: 1, distance: 539, hole_handicap: 18, par: 5)
puts "End --- Creates Holes"


puts "Start --- Creates Scores"
Score.create(golfer_id:1, hole_id:1, strokes:7)
Score.create(golfer_id:1, hole_id:2, strokes:7)
Score.create(golfer_id:1, hole_id:3, strokes:6)
Score.create(golfer_id:1, hole_id:4, strokes:4)
Score.create(golfer_id:1, hole_id:5, strokes:7)
Score.create(golfer_id:1, hole_id:6, strokes:5)
Score.create(golfer_id:1, hole_id:7, strokes:6)
Score.create(golfer_id:1, hole_id:8, strokes:5)
Score.create(golfer_id:1, hole_id:9, strokes:7)
Score.create(golfer_id:1, hole_id:10, strokes:3)
Score.create(golfer_id:1, hole_id:11, strokes:4)
Score.create(golfer_id:1, hole_id:12, strokes:8)
Score.create(golfer_id:1, hole_id:13, strokes:5)
Score.create(golfer_id:1, hole_id:14, strokes:4)
Score.create(golfer_id:1, hole_id:15, strokes:7)
Score.create(golfer_id:1, hole_id:16, strokes:8)
Score.create(golfer_id:1, hole_id:17, strokes:8)
Score.create(golfer_id:1, hole_id:18, strokes:7)
Score.create(golfer_id:2, hole_id:1, strokes:10)
Score.create(golfer_id:2, hole_id:2, strokes:7)
Score.create(golfer_id:2, hole_id:3, strokes:7)
Score.create(golfer_id:2, hole_id:4, strokes:7)
Score.create(golfer_id:2, hole_id:5, strokes:6)
Score.create(golfer_id:2, hole_id:6, strokes:5)
Score.create(golfer_id:2, hole_id:7, strokes:6)
Score.create(golfer_id:2, hole_id:8, strokes:5)
Score.create(golfer_id:2, hole_id:9, strokes:5)
Score.create(golfer_id:2, hole_id:10, strokes:4)
Score.create(golfer_id:2, hole_id:11, strokes:3)
Score.create(golfer_id:2, hole_id:12, strokes:6)
Score.create(golfer_id:2, hole_id:13, strokes:4)
Score.create(golfer_id:2, hole_id:14, strokes:5)
Score.create(golfer_id:2, hole_id:15, strokes:6)
Score.create(golfer_id:2, hole_id:16, strokes:6)
Score.create(golfer_id:2, hole_id:17, strokes:7)
Score.create(golfer_id:2, hole_id:18, strokes:9)
Score.create(golfer_id:3, hole_id:1, strokes:9)
Score.create(golfer_id:3, hole_id:2, strokes:7)
Score.create(golfer_id:3, hole_id:3, strokes:7)
Score.create(golfer_id:3, hole_id:4, strokes:5)
Score.create(golfer_id:3, hole_id:5, strokes:8)
Score.create(golfer_id:3, hole_id:6, strokes:6)
Score.create(golfer_id:3, hole_id:7, strokes:7)
Score.create(golfer_id:3, hole_id:8, strokes:4)
Score.create(golfer_id:3, hole_id:9, strokes:8)
Score.create(golfer_id:3, hole_id:10, strokes:4)
Score.create(golfer_id:3, hole_id:11, strokes:6)
Score.create(golfer_id:3, hole_id:12, strokes:8)
Score.create(golfer_id:3, hole_id:13, strokes:4)
Score.create(golfer_id:3, hole_id:14, strokes:6)
Score.create(golfer_id:3, hole_id:15, strokes:6)
Score.create(golfer_id:3, hole_id:16, strokes:6)
Score.create(golfer_id:3, hole_id:17, strokes:5)
Score.create(golfer_id:3, hole_id:18, strokes:7)
Score.create(golfer_id:4, hole_id:1, strokes:8)
Score.create(golfer_id:4, hole_id:2, strokes:7)
Score.create(golfer_id:4, hole_id:3, strokes:7)
Score.create(golfer_id:4, hole_id:4, strokes:7)
Score.create(golfer_id:4, hole_id:5, strokes:8)
Score.create(golfer_id:4, hole_id:6, strokes:6)
Score.create(golfer_id:4, hole_id:7, strokes:8)
Score.create(golfer_id:4, hole_id:8, strokes:4)
Score.create(golfer_id:4, hole_id:9, strokes:6)
Score.create(golfer_id:4, hole_id:10, strokes:3)
Score.create(golfer_id:4, hole_id:11, strokes:6)
Score.create(golfer_id:4, hole_id:12, strokes:6)
Score.create(golfer_id:4, hole_id:13, strokes:5)
Score.create(golfer_id:4, hole_id:14, strokes:5)
Score.create(golfer_id:4, hole_id:15, strokes:6)
Score.create(golfer_id:4, hole_id:16, strokes:7)
Score.create(golfer_id:4, hole_id:17, strokes:6)
Score.create(golfer_id:4, hole_id:18, strokes:9)
Score.create(golfer_id:5, hole_id:1, strokes:9)
Score.create(golfer_id:5, hole_id:2, strokes:5)
Score.create(golfer_id:5, hole_id:3, strokes:7)
Score.create(golfer_id:5, hole_id:4, strokes:8)
Score.create(golfer_id:5, hole_id:5, strokes:5)
Score.create(golfer_id:5, hole_id:6, strokes:5)
Score.create(golfer_id:5, hole_id:7, strokes:7)
Score.create(golfer_id:5, hole_id:8, strokes:6)
Score.create(golfer_id:5, hole_id:9, strokes:4)
Score.create(golfer_id:5, hole_id:10, strokes:5)
Score.create(golfer_id:5, hole_id:11, strokes:8)
Score.create(golfer_id:5, hole_id:12, strokes:6)
Score.create(golfer_id:5, hole_id:13, strokes:6)
Score.create(golfer_id:5, hole_id:14, strokes:5)
Score.create(golfer_id:5, hole_id:15, strokes:7)
Score.create(golfer_id:5, hole_id:16, strokes:7)
Score.create(golfer_id:5, hole_id:17, strokes:6)
Score.create(golfer_id:5, hole_id:18, strokes:5)
Score.create(golfer_id:6, hole_id:1, strokes:8)
Score.create(golfer_id:6, hole_id:2, strokes:6)
Score.create(golfer_id:6, hole_id:3, strokes:5)
Score.create(golfer_id:6, hole_id:4, strokes:5)
Score.create(golfer_id:6, hole_id:5, strokes:6)
Score.create(golfer_id:6, hole_id:6, strokes:4)
Score.create(golfer_id:6, hole_id:7, strokes:6)
Score.create(golfer_id:6, hole_id:8, strokes:3)
Score.create(golfer_id:6, hole_id:9, strokes:5)
Score.create(golfer_id:6, hole_id:10, strokes:4)
Score.create(golfer_id:6, hole_id:11, strokes:4)
Score.create(golfer_id:6, hole_id:12, strokes:5)
Score.create(golfer_id:6, hole_id:13, strokes:3)
Score.create(golfer_id:6, hole_id:14, strokes:5)
Score.create(golfer_id:6, hole_id:15, strokes:7)
Score.create(golfer_id:6, hole_id:16, strokes:5)
Score.create(golfer_id:6, hole_id:17, strokes:6)
Score.create(golfer_id:6, hole_id:18, strokes:6)
Score.create(golfer_id:7, hole_id:1, strokes:7)
Score.create(golfer_id:7, hole_id:2, strokes:5)
Score.create(golfer_id:7, hole_id:3, strokes:8)
Score.create(golfer_id:7, hole_id:4, strokes:6)
Score.create(golfer_id:7, hole_id:5, strokes:7)
Score.create(golfer_id:7, hole_id:6, strokes:6)
Score.create(golfer_id:7, hole_id:7, strokes:6)
Score.create(golfer_id:7, hole_id:8, strokes:4)
Score.create(golfer_id:7, hole_id:9, strokes:5)
Score.create(golfer_id:7, hole_id:10, strokes:4)
Score.create(golfer_id:7, hole_id:11, strokes:5)
Score.create(golfer_id:7, hole_id:12, strokes:7)
Score.create(golfer_id:7, hole_id:13, strokes:5)
Score.create(golfer_id:7, hole_id:14, strokes:7)
Score.create(golfer_id:7, hole_id:15, strokes:10)
Score.create(golfer_id:7, hole_id:16, strokes:6)
Score.create(golfer_id:7, hole_id:17, strokes:5)
Score.create(golfer_id:7, hole_id:18, strokes:6)
Score.create(golfer_id:8, hole_id:1, strokes:5)
Score.create(golfer_id:8, hole_id:2, strokes:6)
Score.create(golfer_id:8, hole_id:3, strokes:5)
Score.create(golfer_id:8, hole_id:4, strokes:6)
Score.create(golfer_id:8, hole_id:5, strokes:5)
Score.create(golfer_id:8, hole_id:6, strokes:4)
Score.create(golfer_id:8, hole_id:7, strokes:7)
Score.create(golfer_id:8, hole_id:8, strokes:4)
Score.create(golfer_id:8, hole_id:9, strokes:5)
Score.create(golfer_id:8, hole_id:10, strokes:4)
Score.create(golfer_id:8, hole_id:11, strokes:4)
Score.create(golfer_id:8, hole_id:12, strokes:5)
Score.create(golfer_id:8, hole_id:13, strokes:4)
Score.create(golfer_id:8, hole_id:14, strokes:7)
Score.create(golfer_id:8, hole_id:15, strokes:6)
Score.create(golfer_id:8, hole_id:16, strokes:5)
Score.create(golfer_id:8, hole_id:17, strokes:7)
Score.create(golfer_id:8, hole_id:18, strokes:7)
Score.create(golfer_id:9, hole_id:1, strokes:7)
Score.create(golfer_id:9, hole_id:2, strokes:8)
Score.create(golfer_id:9, hole_id:3, strokes:7)
Score.create(golfer_id:9, hole_id:4, strokes:7)
Score.create(golfer_id:9, hole_id:5, strokes:8)
Score.create(golfer_id:9, hole_id:6, strokes:6)
Score.create(golfer_id:9, hole_id:7, strokes:9)
Score.create(golfer_id:9, hole_id:8, strokes:6)
Score.create(golfer_id:9, hole_id:9, strokes:7)
Score.create(golfer_id:9, hole_id:10, strokes:6)
Score.create(golfer_id:9, hole_id:11, strokes:7)
Score.create(golfer_id:9, hole_id:12, strokes:7)
Score.create(golfer_id:9, hole_id:13, strokes:6)
Score.create(golfer_id:9, hole_id:14, strokes:5)
Score.create(golfer_id:9, hole_id:15, strokes:7)
Score.create(golfer_id:9, hole_id:16, strokes:7)
Score.create(golfer_id:9, hole_id:17, strokes:8)
Score.create(golfer_id:9, hole_id:18, strokes:8)
Score.create(golfer_id:10, hole_id:1, strokes:8)
Score.create(golfer_id:10, hole_id:2, strokes:6)
Score.create(golfer_id:10, hole_id:3, strokes:7)
Score.create(golfer_id:10, hole_id:4, strokes:7)
Score.create(golfer_id:10, hole_id:5, strokes:6)
Score.create(golfer_id:10, hole_id:6, strokes:6)
Score.create(golfer_id:10, hole_id:7, strokes:5)
Score.create(golfer_id:10, hole_id:8, strokes:6)
Score.create(golfer_id:10, hole_id:9, strokes:4)
Score.create(golfer_id:10, hole_id:10, strokes:4)
Score.create(golfer_id:10, hole_id:11, strokes:7)
Score.create(golfer_id:10, hole_id:12, strokes:6)
Score.create(golfer_id:10, hole_id:13, strokes:5)
Score.create(golfer_id:10, hole_id:14, strokes:5)
Score.create(golfer_id:10, hole_id:15, strokes:9)
Score.create(golfer_id:10, hole_id:16, strokes:7)
Score.create(golfer_id:10, hole_id:17, strokes:7)
Score.create(golfer_id:10, hole_id:18, strokes:5)
Score.create(golfer_id:11, hole_id:1, strokes:7)
Score.create(golfer_id:11, hole_id:2, strokes:6)
Score.create(golfer_id:11, hole_id:3, strokes:5)
Score.create(golfer_id:11, hole_id:4, strokes:5)
Score.create(golfer_id:11, hole_id:5, strokes:7)
Score.create(golfer_id:11, hole_id:6, strokes:5)
Score.create(golfer_id:11, hole_id:7, strokes:6)
Score.create(golfer_id:11, hole_id:8, strokes:3)
Score.create(golfer_id:11, hole_id:9, strokes:8)
Score.create(golfer_id:11, hole_id:10, strokes:4)
Score.create(golfer_id:11, hole_id:11, strokes:6)
Score.create(golfer_id:11, hole_id:12, strokes:6)
Score.create(golfer_id:11, hole_id:13, strokes:4)
Score.create(golfer_id:11, hole_id:14, strokes:6)
Score.create(golfer_id:11, hole_id:15, strokes:7)
Score.create(golfer_id:11, hole_id:16, strokes:6)
Score.create(golfer_id:11, hole_id:17, strokes:6)
Score.create(golfer_id:11, hole_id:18, strokes:9)
Score.create(golfer_id:12, hole_id:1, strokes:7)
Score.create(golfer_id:12, hole_id:2, strokes:5)
Score.create(golfer_id:12, hole_id:3, strokes:6)
Score.create(golfer_id:12, hole_id:4, strokes:6)
Score.create(golfer_id:12, hole_id:5, strokes:5)
Score.create(golfer_id:12, hole_id:6, strokes:3)
Score.create(golfer_id:12, hole_id:7, strokes:7)
Score.create(golfer_id:12, hole_id:8, strokes:4)
Score.create(golfer_id:12, hole_id:9, strokes:8)
Score.create(golfer_id:12, hole_id:10, strokes:6)
Score.create(golfer_id:12, hole_id:11, strokes:5)
Score.create(golfer_id:12, hole_id:12, strokes:6)
Score.create(golfer_id:12, hole_id:13, strokes:4)
Score.create(golfer_id:12, hole_id:14, strokes:5)
Score.create(golfer_id:12, hole_id:15, strokes:5)
Score.create(golfer_id:12, hole_id:16, strokes:5)
Score.create(golfer_id:12, hole_id:17, strokes:5)
Score.create(golfer_id:12, hole_id:18, strokes:6)
Score.create(golfer_id:13, hole_id:1, strokes:6)
Score.create(golfer_id:13, hole_id:2, strokes:5)
Score.create(golfer_id:13, hole_id:3, strokes:6)
Score.create(golfer_id:13, hole_id:4, strokes:8)
Score.create(golfer_id:13, hole_id:5, strokes:5)
Score.create(golfer_id:13, hole_id:6, strokes:4)
Score.create(golfer_id:13, hole_id:7, strokes:7)
Score.create(golfer_id:13, hole_id:8, strokes:3)
Score.create(golfer_id:13, hole_id:9, strokes:8)
Score.create(golfer_id:13, hole_id:10, strokes:4)
Score.create(golfer_id:13, hole_id:11, strokes:7)
Score.create(golfer_id:13, hole_id:12, strokes:6)
Score.create(golfer_id:13, hole_id:13, strokes:4)
Score.create(golfer_id:13, hole_id:14, strokes:6)
Score.create(golfer_id:13, hole_id:15, strokes:9)
Score.create(golfer_id:13, hole_id:16, strokes:5)
Score.create(golfer_id:13, hole_id:17, strokes:8)
Score.create(golfer_id:13, hole_id:18, strokes:6)
Score.create(golfer_id:14, hole_id:1, strokes:7)
Score.create(golfer_id:14, hole_id:2, strokes:6)
Score.create(golfer_id:14, hole_id:3, strokes:7)
Score.create(golfer_id:14, hole_id:4, strokes:5)
Score.create(golfer_id:14, hole_id:5, strokes:6)
Score.create(golfer_id:14, hole_id:6, strokes:4)
Score.create(golfer_id:14, hole_id:7, strokes:5)
Score.create(golfer_id:14, hole_id:8, strokes:4)
Score.create(golfer_id:14, hole_id:9, strokes:6)
Score.create(golfer_id:14, hole_id:10, strokes:6)
Score.create(golfer_id:14, hole_id:11, strokes:7)
Score.create(golfer_id:14, hole_id:12, strokes:4)
Score.create(golfer_id:14, hole_id:13, strokes:4)
Score.create(golfer_id:14, hole_id:14, strokes:8)
Score.create(golfer_id:14, hole_id:15, strokes:6)
Score.create(golfer_id:14, hole_id:16, strokes:5)
Score.create(golfer_id:14, hole_id:17, strokes:5)
Score.create(golfer_id:14, hole_id:18, strokes:6)
Score.create(golfer_id:15, hole_id:1, strokes:7)
Score.create(golfer_id:15, hole_id:2, strokes:6)
Score.create(golfer_id:15, hole_id:3, strokes:6)
Score.create(golfer_id:15, hole_id:4, strokes:6)
Score.create(golfer_id:15, hole_id:5, strokes:5)
Score.create(golfer_id:15, hole_id:6, strokes:5)
Score.create(golfer_id:15, hole_id:7, strokes:6)
Score.create(golfer_id:15, hole_id:8, strokes:3)
Score.create(golfer_id:15, hole_id:9, strokes:7)
Score.create(golfer_id:15, hole_id:10, strokes:4)
Score.create(golfer_id:15, hole_id:11, strokes:6)
Score.create(golfer_id:15, hole_id:12, strokes:6)
Score.create(golfer_id:15, hole_id:13, strokes:5)
Score.create(golfer_id:15, hole_id:14, strokes:4)
Score.create(golfer_id:15, hole_id:15, strokes:6)
Score.create(golfer_id:15, hole_id:16, strokes:8)
Score.create(golfer_id:15, hole_id:17, strokes:6)
Score.create(golfer_id:15, hole_id:18, strokes:7)
###### SCORE column renamed to STROKES 081719
puts "End --- Creates Scores"